language: generic

python: 3.6

before_install:
#   - sudo add-apt-repository -y ppa:jonathonf/texlive
#   - sudo apt-get -qq update
#   - sudo apt-get install -y --no-install-recommends texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-lang-european texlive-bibtex-extra biber texlive-science latexmk
  - tlmgr init-usertree
  - tlmgr install inconsolata
  # - pip3 install Pygments

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive'
    packages:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
      # - texlive-fonts-extra
      - texlive-lang-european
      - texlive-bibtex-extra
      - biber
      - texlive-science
      - latexmk
      - xzdec # maybe not needed for tlmgr?
      - python-pygments

script:
  - latexmk -pdf -halt-on-error thesis.tex
  # - latexmk -output-directory=build -aux-directory=build -pdf -halt-on-error thesis.tex
  - latexmk -pdf -halt-on-error defence.tex

before_deploy:
  - mkdir pages
  - cp build/thesis.pdf pages/
  - cp build/defence.pdf pages/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: pages
  verbose: true
  on:
    branch: master
    # all_branches: true