language: generic

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/texlive
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-lang-european texlive-bibtex-extra biber latexmk

script:
  - latexmk -pdf -halt-on-error thesis.tex